
DELETE FROM USER WHERE NAME = 'superman';
DELETE FROM USER WHERE NAME = 'tester';

INSERT INTO USER(NAME, TYPE ) VALUES('superman', 'ADMIN');
INSERT INTO USER(NAME, TYPE ) VALUES('tester'  , 'REGULAR');

COMMIT;




